version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r req.txt -t .
  build:
    commands:
      - echo "Build finished for Python 3.12"
artifacts:
  files:
    - '**/*'
