version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - python --version
      - pip install -r req.txt -t .
  build:
    commands:
      - echo "Build phase finished"

artifacts:
  files:
    - '**/*'
