version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12.7
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - '**/*'
