version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing requirements...
      - pip install -r req.txt

  build:
    commands:
      - echo Running build step...
      - python -m unittest discover || echo "No tests found"

  post_build:
    commands:
      - echo Build and install steps completed.

artifacts:
  files:
    - '**/*'
